### ISSUE TITLE
Different network layer structure from DQN

### ISSUE THREAD

**Issue by yumere** [NVlabs/GA3C#14]
When saw [NetworkVP.py code](https://github.com/NVlabs/GA3C/blob/master/ga3c/NetworkVP.py#L79), It has 2 layers of convolutional network and a dense layer. And the above comment says `# As implemented in A3C paper`.

But *[Asynchronous Methods for Deep Reinforcement Learning](http://www.jmlr.org/proceedings/papers/v48/mniha16.pdf)* paper does not describe structure of network layers. So I think that **A3C** has same model structure with **DQN** because of comparing between A3C and DQN.

In DQN, It has 3 layers of convolutional network and a dense layer. But the **GA3C** code is not.

**Comment by mbz** [comment]
Please refer to page 8 of [A3C paper](https://arxiv.org/pdf/1602.01783.pdf):

"The network used a convolutional layer with 16 ﬁlters of size 8 × 8 with stride 4, followed by a convolutional layer with 32 ﬁlters of size 4 × 4 with stride 2, followed by a fully connected layer with 256 hidden units"
