### ISSUE TITLE
Action Repeat Option

### ISSUE THREAD

**Issue by djl11** [NVlabs/GA3C#9]
I've just finished reading the GA3C paper, and I didn't notice any mention of action repeat (as implemented in original Deep-Q paper, and A3C paper). From my understanding, action repeat means that, not only are frames stacked together (into an effective single state) in groups of 4, but actions are also only selected every 4 frames, with these action selections then being carried through (i.e. repeated) until another 4 frames have passed, ready for another action selection.

These correspond to two different hyperparameters from my understanding, one for how many frames to stack (refered to as "m" in Deep-Q methods section), and one for how often to select actions (referred to as "k" in Deep-Q methods section). These are then also explicity referrenced in A3C Experimental Setup section.

I may be wrong, but I've gone through this source code, and from my understanding, different actions are selected every single frame, not every 4th frame (or Kth frame, to be more general). It seems as though there is no option to change this, to more closely replicate DeepMind's A3C approach. I was wondering if this was a design decision? If not, is there any plan to incorporate action replay options into the model, with a parameter in the Config.py file etc. ?

Alternatively, if I've misinterpretted the code (which is entirely possible), I would be grateful if you could point out where/how the action replay is incorporated.

I will try implementing it efficiently myself in the meantime, which you are welcome to use if helpful.

P.s. this code is proving to be extremely useful!
Thanks a lot for sharing!

Dan

**Comment by mbz** [comment]
@djl11 OpenAI gym is enforcing the action repeat and that's why there is no GA3C specific code to handle it. Depending on the postfixes to the name of the environment the frame skip logic is different. Please find more info in the OpenAI gym code [here](https://github.com/openai/gym/blob/d337f4e5719bb8b49f2f9fba1501fe7749fa4d5c/gym/envs/__init__.py).
Also [this thread ](https://github.com/openai/gym/issues/349) is useful.

**Comment by djl11** [comment]
Ahhhh! That makes sense then. Had no idea that was handled inside gym. Thank you very much!
